import { useEffect, useRef, useState } from 'react';
import { Alert, Button, Card, CardContent, Chip, LinearProgress, MenuItem, TextField } from '@mui/material';
import PageHeader from '../../../components/PageHeader';
import CustomDataTable from '../../../components/CustomDataTable';
import { arsipApi } from '../../../libs/arsip_api';
import { formatArsipError } from '../../../libs/arsip_http';
import { usePollingJob } from '../hooks/usePollingJob';
import { reconciliationProgress, runStorageSync, storageAvailability, storageBytes, storageDashboardController, storageDashboardView, storageFilesRequest, storageFileSort, storageSummaryState } from './institutionalArchiveUi';

const emptyFilters = { storage_availability: '', unit_id: '', category_id: '', version: '', deleted: 'exclude', sort: 'file_size_bytes', direction: 'desc' };
const metaDefault = { total: 0, current_page: 1, per_page: 20 };

export default function AdminInstitutionalStorage() {
    const controller = useRef(storageDashboardController());
    const [summary, setSummary] = useState(null); const [files, setFiles] = useState([]); const [meta, setMeta] = useState(metaDefault);
    const [filters, setFilters] = useState(emptyFilters); const [applied, setApplied] = useState(emptyFilters); const [pageSize, setPageSize] = useState(20); const [sortModel, setSortModel] = useState([{ field: 'file_size_bytes', sort: 'desc' }]);
    const [loading, setLoading] = useState(true); const [filesLoading, setFilesLoading] = useState(true); const [summaryError, setSummaryError] = useState(''); const [filesError, setFilesError] = useState(''); const [actionError, setActionError] = useState(''); const [job, setJob] = useState(null);
    const loadSummary = async () => { const capture = controller.current.capture('summary'); setSummaryError(''); setLoading(true); try { const response = await arsipApi.institutionalStorageSummary(); if (capture.valid()) { setSummary(response.data); setSummaryError(''); } } catch (e) { if (capture.valid()) setSummaryError((await formatArsipError(e)).message); } finally { if (capture.valid()) setLoading(false); } };
    const loadFiles = async (page = 1, size = pageSize, next = applied) => { const capture = controller.current.capture('files'); setFilesError(''); setFilesLoading(true); try { const response = await arsipApi.institutionalStorageFiles(storageFilesRequest(page, size, next)); if (capture.valid()) { setFiles(response.data.files || []); setMeta(response.data.pagination || metaDefault); setFilesError(''); } } catch (e) { if (capture.valid()) setFilesError((await formatArsipError(e)).message); } finally { if (capture.valid()) setFilesLoading(false); } };
    useEffect(() => { loadSummary(); loadFiles(); return () => controller.current.close(); }, []);
    const acceptJob = next => { if (!next?.job_id) return; controller.current.resume(next.job_id); setJob(next); };
    const trigger = async () => { const capture = controller.current.beginSync(); if (!capture) return; setActionError(''); try { await runStorageSync({ capture, trigger: arsipApi.triggerInstitutionalStorageReconciliation, onJob: acceptJob, onError: setActionError, formatError: formatArsipError }); } finally { controller.current.release(capture); } };
    usePollingJob({ enabled: ['queued', 'running'].includes(job?.status), jobId: job?.job_id, pollFn: async jobId => (await arsipApi.institutionalStorageReconciliationJob(jobId)).data.job, terminalStatuses: ['completed', 'failed'], onUpdate: next => { if (String(controller.current.currentJob()) === String(next?.job_id)) setJob(next); }, onTerminal: ({ data }) => { if (String(controller.current.currentJob()) === String(data.job_id)) { setJob(data); loadSummary(); loadFiles(meta.current_page); } } });
    const apply = () => { controller.current.change(); setJob(null); setApplied(filters); loadFiles(1, pageSize, filters); };
    const error = actionError || summaryError || filesError; const cards = summary ? storageSummaryState(summary) : null; const progress = reconciliationProgress(job); const view = storageDashboardView({ loading, error, summary });
    const columns = [{ field: 'display_filename', headerName: 'File', flex: 1 }, { field: 'archive_title', headerName: 'Arsip', flex: 1, sortable: false }, { field: 'unit_name', headerName: 'Unit', sortable: false }, { field: 'category_name', headerName: 'Folder', sortable: false, valueGetter: value => value || 'Tanpa Folder' }, { field: 'file_size_bytes', headerName: 'Ukuran', renderCell: ({ value }) => storageBytes(value) }, { field: 'storage_availability', headerName: 'Ketersediaan', renderCell: ({ value }) => <Chip size="small" label={storageAvailability(value)} color={value === 'available' ? 'success' : value === 'missing' ? 'error' : 'default'} /> }, { field: 'created_at', headerName: 'Dibuat' }];
    return <div className="p-4 space-y-4" data-storage-view={view}><PageHeader title="Storage Arsip Lembaga" subtitle="Ringkasan metadata database; bukan kapasitas provider storage" />{error && <Alert severity="error">{error}</Alert>}
        {cards && <div className="grid md:grid-cols-4 gap-3">{[['Total seluruh versi', cards.total], ['Versi current', cards.current], ['Jumlah versi', cards.versions], ['Soft-deleted', cards.deleted]].map(([label, value]) => <Card key={label}><CardContent><div className="text-sm">{label}</div><strong>{label === 'Jumlah versi' ? value : storageBytes(value)}</strong></CardContent></Card>)}</div>}
        {summary && <div className="grid md:grid-cols-2 gap-3"><Card><CardContent><strong>Ketersediaan DB</strong><div className="flex gap-3 mt-2">{['available', 'missing', 'unknown'].map(key => <Chip key={key} label={`${key}: ${summary.availability?.[key] || 0}`} />)}</div></CardContent></Card><Card><CardContent><strong>Batas lunak internal</strong><div>{cards.limit ? `${storageBytes(cards.total)} / ${storageBytes(cards.limit)} (${summary.soft_limit_percent || 0}%)` : 'Tidak diatur'}</div><div className="text-sm">Label disk: {summary.storage_disk_label || '-'}. Bukan kapasitas provider.</div></CardContent></Card></div>}
        {summary?.reconciliation_stale && <Alert severity="warning">Rekonsiliasi terakhir belum ada atau sudah lebih dari 24 jam.</Alert>}
        <Card><CardContent><div className="flex flex-wrap justify-between gap-2"><div><strong>Rekonsiliasi storage</strong><div>Terakhir: {summary?.latest_reconciliation?.finished_at || 'Belum pernah'}</div></div><Button variant="contained" disabled={controller.current.busy() || ['queued', 'running'].includes(job?.status)} onClick={trigger}>Jalankan rekonsiliasi</Button></div>{job && <div className="mt-3"><div>Status: {progress.status} — {job.checked_files || 0}/{job.total_files || 0}</div><LinearProgress variant="determinate" value={progress.percent} /><div>Available {job.available_files || 0}, missing {job.missing_files || 0}, gagal diperiksa {job.failed_files || 0}</div></div>}</CardContent></Card>
        <div className="flex flex-wrap gap-2"><TextField size="small" select label="Ketersediaan" value={filters.storage_availability} onChange={e => setFilters({ ...filters, storage_availability: e.target.value })}><MenuItem value="">Semua</MenuItem>{['available', 'missing', 'unknown'].map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField size="small" label="ID unit" type="number" value={filters.unit_id} onChange={e => setFilters({ ...filters, unit_id: e.target.value })} /><TextField size="small" label="ID folder / root" value={filters.category_id} onChange={e => setFilters({ ...filters, category_id: e.target.value })} /><TextField size="small" select label="Versi" value={filters.version} onChange={e => setFilters({ ...filters, version: e.target.value })}><MenuItem value="">Semua</MenuItem><MenuItem value="current">Current</MenuItem><MenuItem value="historical">Historical</MenuItem></TextField><Button onClick={apply}>Terapkan</Button></div>
        <CustomDataTable rows={files} columns={columns} loading={filesLoading} getRowId={row => row.file_id} paginationMode="server" sortingMode="server" rowCount={meta.total || 0} paginationModel={{ page: (meta.current_page || 1) - 1, pageSize }} pageSizeOptions={[10, 20, 50, 100]} onPaginationModelChange={model => { setPageSize(model.pageSize); loadFiles(model.page + 1, model.pageSize); }} sortModel={sortModel} onSortModelChange={model => { const sort = storageFileSort(model); setSortModel(model); setApplied(current => ({ ...current, ...sort })); loadFiles(1, pageSize, { ...applied, ...sort }); }} />
        {summary && <div className="grid md:grid-cols-2 gap-3"><Card><CardContent><strong>Penggunaan per unit (maks. 50)</strong>{(summary.by_unit || []).map(x => <div key={x.unit_id}>{x.name}: {storageBytes(x.bytes)} ({x.files} file)</div>)}</CardContent></Card><Card><CardContent><strong>Penggunaan per folder (maks. 50)</strong>{(summary.by_category || []).map(x => <div key={x.category_id ?? 'root'}>{x.name}: {storageBytes(x.bytes)} ({x.files} file)</div>)}</CardContent></Card></div>}
    </div>;
}
