import { useEffect, useRef, useState } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, MenuItem, TextField } from '@mui/material';
import { Link } from 'react-router-dom';
import PageHeader from '../../../components/PageHeader';
import CustomDataTable from '../../../components/CustomDataTable';
import { arsipApi } from '../../../libs/arsip_api';
import { formatArsipError } from '../../../libs/arsip_http';
import { fetchAllPages } from './InstitutionalClassificationSettings';
import { institutionalArchiveTableController, uploadPercent, validationErrors } from './institutionalArchiveUi';

const empty = { title: '', unit_id: '', category_id: '', document_number: '', document_year: '', document_date: '', received_date: '', description: '', access_level: 'internal', retention_note: '', tags: '', file: null };
const initialFilters = { search: '', unit_id: '', category_id: '', document_year: '', access_level: '', storage_availability: '', uploader_id: '' };
const initialAppliedFilters = { ...initialFilters, sort: 'created_at', direction: 'desc' };
const unwrap = (response, key) => response?.data?.[key] ?? [];

export default function AdminInstitutionalArchives() {
    const [rows, setRows] = useState([]); const [units, setUnits] = useState([]); const [categories, setCategories] = useState([]);
    const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [fieldErrors, setFieldErrors] = useState({}); const [success, setSuccess] = useState('');
    const [filters, setFilters] = useState(initialFilters); const [appliedFilters, setAppliedFilters] = useState(initialAppliedFilters); const [sortModel, setSortModel] = useState([]); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(25); const [pagination, setPagination] = useState({ total: 0, per_page: 25 });
    const [open, setOpen] = useState(false); const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false); const [uploadProgress, setUploadProgress] = useState(null); const loadingId = useRef(0);
    const load = async (nextPage = page, nextFilters = appliedFilters, nextPageSize = pageSize) => { const id = ++loadingId.current; setLoading(true); setError(''); try { const response = await arsipApi.institutionalArchives({ page: nextPage, per_page: nextPageSize, ...nextFilters }); if (id !== loadingId.current) return; setRows(unwrap(response, 'archives')); setPagination(response.data.pagination); } catch (e) { if (id === loadingId.current) { setRows([]); setError((await formatArsipError(e)).message); } } finally { if (id === loadingId.current) setLoading(false); } };
    useEffect(() => { Promise.all([fetchAllPages(arsipApi.institutionalUnits, 'units', false), fetchAllPages(arsipApi.institutionalCategories, 'categories', false)]).then(([u, c]) => { setUnits(u.filter(x => !x.deleted_at)); setCategories(c.filter(x => !x.deleted_at)); }).catch(async e => setError((await formatArsipError(e)).message)); load(1); return () => { loadingId.current += 1; }; }, []);
    const submit = async () => { if (saving) return; setSaving(true); setError(''); setFieldErrors({}); try { const data = new FormData(); Object.entries(form).forEach(([k, v]) => { if (v !== '' && v !== null) { if (k === 'tags') v.split(',').map(x => x.trim()).filter(Boolean).forEach(tag => data.append('tags[]', tag)); else data.append(k, v); } }); setUploadProgress(0); await arsipApi.uploadInstitutionalArchive(data, event => { const percent = uploadPercent(event); if (percent !== null) setUploadProgress(percent); }); setSuccess('Arsip berhasil diupload.'); setOpen(false); setForm(empty); const next = institutionalArchiveTableController.upload(pageSize, appliedFilters); setPage(next.state.page); await load(next.request.page, appliedFilters, next.request.per_page); } catch (e) { const formatted = await formatArsipError(e); setError(formatted.message); setFieldErrors(validationErrors(formatted)); } finally { setSaving(false); setUploadProgress(null); } };
    const change = (key, value) => setFilters(current => ({ ...current, [key]: value }));
    const apply = () => { const next = institutionalArchiveTableController.filter(filters, pageSize, appliedFilters); setAppliedFilters(next.state.filters); setPage(next.state.page); load(next.request.page, next.state.filters, next.request.per_page); };
    const handlePaginationChange = model => { const next = institutionalArchiveTableController.pagination(model, pageSize, appliedFilters); setPage(next.state.page); setPageSize(next.state.pageSize); load(next.request.page, appliedFilters, next.request.per_page); };
    const handleSortChange = model => { const next = institutionalArchiveTableController.sort(model, pageSize, appliedFilters); setSortModel(next.state.sortModel); setAppliedFilters(next.state.filters); setPage(next.state.page); load(next.request.page, next.state.filters, next.request.per_page); };
    const columns = [{ field: 'title', headerName: 'Judul', flex: 1 }, { field: 'document_number', headerName: 'Nomor', sortable: false, renderCell: ({ row }) => row.document_number || '-' }, { field: 'unit', headerName: 'Unit', sortable: false, renderCell: ({ row }) => row.unit?.name || '-' }, { field: 'category', headerName: 'Folder', sortable: false, renderCell: ({ row }) => row.category?.name || 'Tanpa Folder' }, { field: 'document_date', headerName: 'Tanggal', renderCell: ({ row }) => row.document_date?.slice(0, 10) || '-' }, { field: 'version', headerName: 'Versi', sortable: false, renderCell: ({ row }) => row.current_file?.version_number || 1 }, { field: 'size', headerName: 'Ukuran', renderCell: ({ row }) => row.current_file?.file_size_bytes || 0 }, { field: 'status', headerName: 'Status', sortable: false, renderCell: ({ row }) => row.current_file?.storage_availability || 'unknown' }, { field: 'actions', headerName: 'Aksi', sortable: false, renderCell: ({ row }) => <Button component={Link} to={`/home/arsip-lembaga/${row.institutional_archive_id}`} size="small">Detail</Button> }];
    const input = (key, label, props = {}) => <TextField size="small" label={label} value={filters[key]} onChange={e => change(key, e.target.value)} {...props} />;
    const table = institutionalArchiveTableController.view({ loading, error, rows });
    return <div className="p-4 space-y-4" data-table-view={table.state}><PageHeader title="Arsip Lembaga" subtitle="Arsip privat bersama seluruh admin" />{error && <Alert severity="error">{error}</Alert>}{success && <Alert severity="success">{success}</Alert>}
        <div className="flex flex-wrap gap-2">{input('search', 'Cari')}{input('unit_id', 'Unit', { select: true, children: [<MenuItem key="all" value="">Semua unit</MenuItem>, ...units.map(x => <MenuItem key={x.unit_id} value={x.unit_id}>{x.name}</MenuItem>)] })}{input('category_id', 'Folder', { select: true, children: [<MenuItem key="all" value="">Semua folder</MenuItem>, <MenuItem key="root" value="root">Tanpa Folder</MenuItem>, ...categories.map(x => <MenuItem key={x.category_id} value={x.category_id}>{x.name}</MenuItem>)] })}{input('document_year', 'Tahun', { type: 'number' })}{input('access_level', 'Akses', { select: true, children: [<MenuItem key="all" value="">Semua</MenuItem>, <MenuItem key="internal" value="internal">Internal</MenuItem>, <MenuItem key="restricted" value="restricted">Restricted</MenuItem>] })}{input('storage_availability', 'Storage', { select: true, children: [<MenuItem key="all" value="">Semua</MenuItem>, ...['available', 'missing', 'unknown'].map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)] })}{input('uploader_id', 'ID uploader', { type: 'number' })}<Button variant="outlined" onClick={apply}>Terapkan</Button><Button component={Link} to="/home/arsip-lembaga/sampah">Sampah</Button><Button variant="contained" onClick={() => { setForm(empty); setFieldErrors({}); setOpen(true); }}>Upload Arsip</Button></div>
        <CustomDataTable {...table.props} columns={columns} getRowId={row => row.institutional_archive_id} pageSize={pageSize} pageSizeOptions={[10, 25, 50, 100]} paginationMode="server" rowCount={pagination.total ?? 0} paginationModel={{ page: page - 1, pageSize }} onPaginationModelChange={handlePaginationChange} sortingMode="server" sortModel={sortModel} onSortModelChange={handleSortChange} />
        <Dialog open={open} onClose={() => !saving && setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Upload Arsip Lembaga</DialogTitle><DialogContent className="space-y-4"><Button component="label" variant="outlined" fullWidth sx={{ mt: 1 }}>{form.file ? `${form.file.name} — ${form.file.size} byte — ${form.file.type || 'unknown'}` : 'Pilih file'}<input hidden type="file" onChange={e => setForm({ ...form, file: e.target.files[0] })} /></Button>{fieldErrors.file && <Alert severity="error">{fieldErrors.file.join(' ')}</Alert>}
            {['title', 'document_number', 'document_year', 'document_date', 'received_date', 'description', 'retention_note', 'tags'].map(key => <TextField key={key} fullWidth required={key === 'title'} type={key.includes('date') ? 'date' : key === 'document_year' ? 'number' : 'text'} multiline={['description', 'retention_note'].includes(key)} label={{ title: 'Judul', document_number: 'Nomor dokumen', document_year: 'Tahun dokumen', document_date: 'Tanggal dokumen', received_date: 'Tanggal diterima', description: 'Deskripsi', retention_note: 'Catatan retensi', tags: 'Tags, pisahkan koma' }[key]} InputLabelProps={key.includes('date') ? { shrink: true } : undefined} value={form[key]} error={Boolean(fieldErrors[key])} helperText={fieldErrors[key]?.join(' ')} onChange={e => setForm({ ...form, [key]: e.target.value })} />)}
            <TextField select fullWidth required label="Unit" value={form.unit_id} error={Boolean(fieldErrors.unit_id)} helperText={fieldErrors.unit_id?.join(' ')} onChange={e => setForm({ ...form, unit_id: e.target.value })}>{units.map(x => <MenuItem key={x.unit_id} value={x.unit_id}>{x.name}</MenuItem>)}</TextField><TextField select fullWidth label="Folder" value={form.category_id} error={Boolean(fieldErrors.category_id)} helperText={fieldErrors.category_id?.join(' ') || ' '} onChange={e => setForm({ ...form, category_id: e.target.value })}><MenuItem value="">Tanpa Folder</MenuItem>{categories.map(x => <MenuItem key={x.category_id} value={x.category_id}>{x.name}</MenuItem>)}</TextField><TextField select fullWidth label="Akses" value={form.access_level} error={Boolean(fieldErrors.access_level)} helperText={fieldErrors.access_level?.join(' ') || ' '} onChange={e => setForm({ ...form, access_level: e.target.value })}><MenuItem value="internal">Internal</MenuItem><MenuItem value="restricted">Restricted</MenuItem></TextField>
            {uploadProgress !== null && <div><LinearProgress variant="determinate" value={uploadProgress} /><div className="text-sm mt-1">Upload {uploadProgress}%</div></div>}
            {form.document_number && !form.document_date && !form.document_year && <Alert severity="warning">Tanggal atau tahun wajib ketika nomor dokumen diisi.</Alert>}
        </DialogContent><DialogActions><Button disabled={saving} onClick={() => setOpen(false)}>Batal</Button><Button disabled={saving || !form.title || !form.unit_id || !form.file || Boolean(form.document_number && !form.document_date && !form.document_year)} onClick={submit}>{saving ? 'Menyimpan...' : 'Simpan'}</Button></DialogActions></Dialog>
    </div>;
}
