import { useEffect, useRef, useState } from 'react';
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, MenuItem, Pagination, Stack, Tab, Tabs, TextField } from '@mui/material';
import ArrowBackOutlined from '@mui/icons-material/ArrowBackOutlined';
import { Link, useNavigate, useParams } from 'react-router-dom';
import PageHeader from '../../../components/PageHeader';
import { arsipApi } from '../../../libs/arsip_api';
import { formatArsipError } from '../../../libs/arsip_http';
import { fetchAllPages } from './InstitutionalClassificationSettings';
import { institutionalArchiveRouteReset, requestSequence, retryVersionRefresh, routeActionAllowed, routeLifecycle, runDownload, runExactVersionDownload, runPreview, runVersionUpload, runArchiveDelete, safeTimelineItem, timelineRequest, timelineView, validationErrors, versionHistoryRequest, versionHistoryState, versionHistoryView } from './institutionalArchiveUi';
import InstitutionalDistributionPanel from './InstitutionalDistributionPanel';

const metadataFields = ['title', 'document_number', 'document_year', 'document_date', 'received_date', 'unit_id', 'description', 'access_level', 'retention_note', 'tags'];
const metadataLabels = { title: 'Judul', document_number: 'Nomor dokumen', document_year: 'Tahun dokumen', document_date: 'Tanggal dokumen', received_date: 'Tanggal diterima', description: 'Deskripsi', retention_note: 'Catatan retensi', tags: 'Tag' };
const metadataPayload = form => Object.fromEntries(metadataFields.map(key => [key, key === 'tags' ? String(form[key] || '').split(',').map(x => x.trim()).filter(Boolean) : form[key] === '' ? null : form[key]]));

export default function AdminInstitutionalArchiveDetail() {
    const { id } = useParams(); const navigate = useNavigate(); const currentRouteId = useRef(id); currentRouteId.current = id; const versionInput = useRef(null); const deleteLock = useRef(false); const uploadLock = useRef(false); const retryLock = useRef(false); const retryRequests = useRef(requestSequence()); const lifecycleRef = useRef(routeLifecycle(id, archiveId => String(currentRouteId.current) === String(archiveId))); const detailRequests = useRef(requestSequence()); const historyRequests = useRef(requestSequence()); const [archive, setArchive] = useState(null); const [units, setUnits] = useState([]); const [categories, setCategories] = useState([]); const [form, setForm] = useState({}); const [moveCategory, setMoveCategory] = useState('');
    const [tab, setTab] = useState(0); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [downloading, setDownloading] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [refreshWarning, setRefreshWarning] = useState('');
    const [metadataErrors, setMetadataErrors] = useState({}); const [moveErrors, setMoveErrors] = useState({}); const [versions, setVersions] = useState([]); const [versionPage, setVersionPage] = useState(1); const [versionPages, setVersionPages] = useState(1); const [historyInitialLoading, setHistoryInitialLoading] = useState(true); const [historyPageLoading, setHistoryPageLoading] = useState(false); const [historyError, setHistoryError] = useState(''); const [versionFile, setVersionFile] = useState(null); const [reason, setReason] = useState(''); const [versionProgress, setVersionProgress] = useState(null); const [deleteOpen, setDeleteOpen] = useState(false); const [deleteReason, setDeleteReason] = useState(''); const [activities, setActivities] = useState([]); const [timelinePage, setTimelinePage] = useState(1); const [timelinePages, setTimelinePages] = useState(1); const [timelineInitialLoading, setTimelineInitialLoading] = useState(true); const [timelinePageLoading, setTimelinePageLoading] = useState(false); const [timelineError, setTimelineError] = useState(''); const timelineRequests = useRef(requestSequence());
    const loadVersions = async (lifecycle, requests, archiveId, page = versionPage) => { const sequence = requests.next(); const valid = () => lifecycle.valid() && requests.valid(sequence); if (valid()) { if (versions.length) setHistoryPageLoading(true); else setHistoryInitialLoading(true); setHistoryError(''); } try { const response = await arsipApi.institutionalArchiveVersions(archiveId, versionHistoryRequest(page)); if (!valid()) return; setVersions(versionHistoryState(response.data.versions)); setVersionPages(response.data.pagination.last_page); setVersionPage(page); } catch (e) { if (valid()) setHistoryError((await formatArsipError(e)).message); throw e; } finally { if (valid()) { setHistoryInitialLoading(false); setHistoryPageLoading(false); } } };
    const loadTimeline = async (lifecycle, requests, archiveId, page = 1) => { const sequence = requests.next(); const valid = () => lifecycle.valid() && requests.valid(sequence); if (valid()) { if (activities.length) setTimelinePageLoading(true); else setTimelineInitialLoading(true); setTimelineError(''); } try { const response = await arsipApi.institutionalArchiveTimeline(archiveId, timelineRequest(page)); if (!valid()) return; setActivities((response.data.activities || []).map(safeTimelineItem)); setTimelinePage(page); setTimelinePages(response.data.pagination.last_page); } catch (e) { if (valid()) setTimelineError((await formatArsipError(e)).message); } finally { if (valid()) { setTimelineInitialLoading(false); setTimelinePageLoading(false); } } };
    const load = async (lifecycle, requests, archiveId) => { const sequence = requests.next(); const valid = () => lifecycle.valid() && requests.valid(sequence); if (valid()) { setLoading(true); setError(''); } try { const response = await arsipApi.institutionalArchive(archiveId); if (!valid()) return; const item = response.data.archive; setArchive(item); setForm({ ...item, document_date: item.document_date?.slice(0, 10) || '', received_date: item.received_date?.slice(0, 10) || '', tags: (item.tags || []).join(', ') }); setMoveCategory(item.category_id || ''); } catch (e) { if (valid()) setError((await formatArsipError(e)).message); throw e; } finally { if (valid()) setLoading(false); } };
    useEffect(() => { const reset = institutionalArchiveRouteReset(); setSaving(reset.saving); setDownloading(reset.downloading); setVersionProgress(reset.versionProgress); setVersions(reset.versions); setVersionPage(reset.versionPage); setVersionPages(reset.versionPages); setHistoryInitialLoading(reset.historyInitialLoading); setHistoryPageLoading(reset.historyPageLoading); setHistoryError(reset.historyError); setArchive(reset.archive); setForm(reset.form); setSuccess(reset.success); setError(reset.error); setRefreshWarning(reset.refreshWarning); setVersionFile(reset.versionFile); setReason(reset.reason); setLoading(true); const lifecycle = routeLifecycle(id, archiveId => String(currentRouteId.current) === String(archiveId)); const detailSequence = requestSequence(); const historySequence = requestSequence(); const retrySequence = requestSequence(); retryRequests.current = retrySequence; lifecycleRef.current = lifecycle; detailRequests.current = detailSequence; historyRequests.current = historySequence; load(lifecycle, detailSequence, id).catch(() => {}); loadVersions(lifecycle, historySequence, id, 1).catch(() => {}); timelineRequests.current = requestSequence(); setActivities([]); setTimelinePage(1); setTimelinePages(1); setTimelineInitialLoading(true); setTimelinePageLoading(false); setTimelineError(''); loadTimeline(lifecycle, timelineRequests.current, id, 1); Promise.all([fetchAllPages(arsipApi.institutionalUnits, 'units', false), fetchAllPages(arsipApi.institutionalCategories, 'categories', false)]).then(([u, c]) => { if (lifecycle.valid()) { setUnits(u.filter(x => !x.deleted_at)); setCategories(c.filter(x => !x.deleted_at)); } }).catch(async e => { if (lifecycle.valid()) setError((await formatArsipError(e)).message); }); return () => { lifecycle.invalidate(); detailSequence.invalidate(); historySequence.invalidate(); retrySequence.invalidate(); timelineRequests.current.invalidate(); }; }, [id]);
    const run = async (action, message, setFieldErrors) => { const lifecycle = lifecycleRef.current; const archiveId = id; if (saving || !lifecycle.valid()) return; setSaving(true); setError(''); setFieldErrors({}); try { await action(); if (lifecycle.valid()) setSuccess(message); await load(lifecycle, detailRequests.current, archiveId); } catch (e) { const formatted = await formatArsipError(e); if (lifecycle.valid()) { setError(formatted.message); setFieldErrors(validationErrors(formatted)); } } finally { if (lifecycle.valid()) setSaving(false); } };
    const preview = () => { const lifecycle = lifecycleRef.current; const archiveId = id; if (lifecycle.valid()) setError(''); runPreview(window.open.bind(window), () => arsipApi.previewInstitutionalArchive(archiveId), URL, value => { if (lifecycle.valid()) setError(value); }, formatArsipError, setTimeout, lifecycle); };
    const download = async () => { const lifecycle = lifecycleRef.current; const item = archive; if (downloading || !lifecycle.valid()) return; setDownloading(true); setError(''); await runDownload(() => arsipApi.downloadInstitutionalArchive(item), value => { if (lifecycle.valid()) setError(value); }, formatArsipError); if (lifecycle.valid()) setDownloading(false); };
    const retryRefresh = () => { const lifecycle = lifecycleRef.current; const archiveId = id; const requests = retryRequests.current; if (retryLock.current || !lifecycle.valid()) return false; retryLock.current = true; const sequence = requests.next(); const retryLifecycle = { valid: () => lifecycle.valid() && requests.valid(sequence) }; return retryVersionRefresh({ lifecycle: retryLifecycle, refreshDetail: () => load(lifecycle, detailRequests.current, archiveId), refreshHistory: () => loadVersions(lifecycle, historyRequests.current, archiveId, 1), onSuccess: () => { if (retryLifecycle.valid()) { setRefreshWarning(''); setSuccess('Versi baru berhasil diupload dan data telah disinkronkan.'); } }, onError: async e => { if (retryLifecycle.valid()) setRefreshWarning(`Upload sudah tersimpan, tetapi sinkronisasi gagal: ${(await formatArsipError(e)).message}`); } }).finally(() => { retryLock.current = false; }); };
    const historyView = versionHistoryView({ initialLoading: historyInitialLoading, pageLoading: historyPageLoading, error: historyError, rows: versions }); const activityView = timelineView({ initialLoading: timelineInitialLoading, pageLoading: timelinePageLoading, error: timelineError, rows: activities });
    if (loading) return <div className="p-4">Memuat detail arsip...</div>;
    if (!archive) return <div className="p-4"><Alert severity="error">{error || 'Arsip tidak ditemukan.'}</Alert><Button component={Link} to="/home/arsip-lembaga">Kembali</Button></div>;
    const file = archive.current_file;
    const show = value => value === null || value === undefined || value === '' ? '-' : value;
    const date = value => value ? new Date(value).toLocaleString('id-ID') : '-';
    const tags = Array.isArray(archive.tags) && archive.tags.length ? archive.tags.join(', ') : '-';
    return <div className="p-4 space-y-4"><PageHeader title={archive.title} subtitle="Detail metadata, versi, aktivitas, dan distribusi arsip lembaga." breadcrumbs={[{ label: 'Arsip Lembaga', href: '/home/arsip-lembaga' }, { label: 'Detail' }]} actions={<Button component={Link} to="/home/arsip-lembaga" variant="outlined" startIcon={<ArrowBackOutlined />}>Kembali</Button>} />{error && <Alert severity="error">{error}</Alert>}{refreshWarning && <Alert severity="warning" action={<Button onClick={retryRefresh}>Coba sinkronkan lagi</Button>}>{refreshWarning}</Alert>}{success && !refreshWarning && <Alert severity="success">{success}</Alert>}
        <div className="grid md:grid-cols-2 gap-3 p-4">
            <div>Nomor dokumen: {show(archive.document_number)}</div><div>Tahun dokumen: {show(archive.document_year)}</div>
            <div>Tanggal dokumen: {show(archive.document_date?.slice(0, 10))}</div><div>Tanggal diterima: {show(archive.received_date?.slice(0, 10))}</div>
            <div>Unit: {show(archive.unit?.name)}</div><div>Folder: {archive.category?.name || 'Tanpa Folder'}</div>
            <div>Akses: {show(archive.access_level)}</div><div>Tags: {tags}</div>
            <div className="md:col-span-2">Deskripsi: {show(archive.description)}</div><div className="md:col-span-2">Catatan retensi: {show(archive.retention_note)}</div>
            <div>Nama file: {show(file?.display_filename)}</div><div>Versi: {show(file?.version_number)}</div>
            <Accordion defaultExpanded={false} className="md:col-span-2"><AccordionSummary>Metadata teknis dan sistem</AccordionSummary><AccordionDetails><div className="grid md:grid-cols-2 gap-3"><div>Tipe file: {show(file?.mime_type)}</div><div>Ukuran file: {file?.file_size_bytes === null || file?.file_size_bytes === undefined ? '-' : `${file.file_size_bytes} byte`}</div><div>Ketersediaan storage: {show(file?.storage_availability)}</div><div>Uploader ID: {show(file?.uploaded_by_user_id)}</div><div>Creator ID: {show(archive.created_by_user_id)}</div><div>Updater ID: {show(archive.updated_by_user_id)}</div><div>Dibuat: {date(archive.created_at)}</div><div>Diperbarui: {date(archive.updated_at)}</div></div></AccordionDetails></Accordion>
        </div>
        <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} useFlexGap flexWrap="wrap"><Button variant="contained" onClick={preview}>Pratinjau</Button><Button variant="outlined" disabled={downloading} onClick={download}>{downloading ? 'Mengunduh...' : 'Unduh'}</Button><Button variant="text" color="error" disabled={saving} onClick={() => setDeleteOpen(true)}>Hapus</Button></Stack><Dialog open={deleteOpen} onClose={() => !saving && setDeleteOpen(false)}><DialogTitle>Hapus arsip?</DialogTitle><DialogContent><TextField autoFocus required fullWidth multiline label="Alasan penghapusan" value={deleteReason} onChange={e => setDeleteReason(e.target.value)} /></DialogContent><DialogActions><Button disabled={saving} onClick={() => setDeleteOpen(false)}>Batal</Button><Button color="error" disabled={saving || !deleteReason.trim()} onClick={() => { const lifecycle = lifecycleRef.current; const archiveId = id; const displayedArchiveId = archive?.institutional_archive_id; const routeId = currentRouteId.current; if (deleteLock.current) return false; setSaving(true); setError(''); return runArchiveDelete({ lock: deleteLock, lifecycle, reason: deleteReason, archiveId, currentArchiveId: routeId, displayedArchiveId, action: arsipApi.deleteInstitutionalArchive, navigate: () => navigate('/home/arsip-lembaga'), onError: setError, formatError: formatArsipError }).finally(() => { if (lifecycle.valid() && String(currentRouteId.current) === String(routeId)) setSaving(false); }); }}>Hapus</Button></DialogActions></Dialog>
        <div className="p-3 space-y-3"><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable" scrollButtons="auto" aria-label="Bagian detail arsip"><Tab id="archive-tab-versions" aria-controls="archive-panel-versions" label="Versi & Aktivitas" /><Tab id="archive-tab-distribution" aria-controls="archive-panel-distribution" label="Distribusi" /><Tab id="archive-tab-metadata" aria-controls="archive-panel-metadata" label="Kelola Metadata" /></Tabs>
        <Box role="tabpanel" id="archive-panel-versions" aria-labelledby="archive-tab-versions" hidden={tab !== 0} tabIndex={tab === 0 ? 0 : undefined} className="space-y-4">
        <h2 className="font-bold">Unggah versi baru</h2><div className="grid md:grid-cols-2 gap-3"><TextField type="file" inputRef={versionInput} inputProps={{ accept: '.pdf,.jpg,.jpeg,.png' }} onChange={e => setVersionFile(e.target.files?.[0] || null)} /><TextField required label="Alasan perubahan" value={reason} onChange={e => setReason(e.target.value)} /></div>{versionProgress !== null && <LinearProgress variant="determinate" value={versionProgress} />}<Button disabled={saving || !versionFile || !reason.trim()} onClick={() => { const lifecycle = lifecycleRef.current; const archiveId = currentRouteId.current; if (!routeActionAllowed(lifecycle, archiveId, archive?.institutional_archive_id)) return false; return runVersionUpload({ busy: saving, lock: uploadLock, lifecycle, file: versionFile, reason, fileInput: versionInput, upload: (data, progress) => arsipApi.uploadInstitutionalArchiveVersion(archiveId, data, progress), refreshDetail: () => load(lifecycle, detailRequests.current, archiveId), refreshHistory: page => loadVersions(lifecycle, historyRequests.current, archiveId, page), onBusy: value => { if (lifecycle.valid()) setSaving(value); }, onProgress: value => { if (lifecycle.valid()) setVersionProgress(value); }, onSuccess: () => { if (lifecycle.valid()) { setVersionFile(null); setReason(''); setRefreshWarning(''); setSuccess('Versi baru berhasil diupload.'); } }, onPartialSuccess: async value => { if (lifecycle.valid()) { setVersionFile(null); setReason(''); setSuccess(''); setRefreshWarning(`Upload sudah tersimpan, tetapi sinkronisasi gagal: ${value?.message || value}`); } }, onError: value => { if (lifecycle.valid()) setError(value?.message || value); }, formatError: formatArsipError }); }}>Unggah versi</Button>
        <h2 className="font-bold">Riwayat versi</h2>{historyView === 'loading' ? <div>Memuat riwayat versi...</div> : historyView === 'error' ? <Alert severity="error">{historyError}</Alert> : historyView === 'empty' ? <div>Belum ada riwayat versi.</div> : <div className="space-y-2">{historyPageLoading && <LinearProgress />}{versions.map(version => <div key={version.file_id} className="flex flex-wrap gap-3 p-3 border rounded"><strong>Versi {version.version_number}{version.current_label ? ` (${version.current_label})` : ''}</strong><span>{version.display_filename}</span><span>{version.file_size_bytes} byte</span><span>Uploader ID: {version.uploaded_by_user_id}</span><span>{date(version.created_at)}</span><span>Checksum: {version.checksum_sha256}</span><span>Alasan: {version.version_reason || '-'}</span><Button size="small" onClick={() => { const lifecycle = lifecycleRef.current; const archiveId = id; runExactVersionDownload({ lifecycle, currentArchiveId: () => currentRouteId.current, displayedArchiveId: () => archive?.institutional_archive_id, download: arsipApi.downloadInstitutionalArchiveVersion, archiveId, version, onError: setError, formatError: formatArsipError }); }}>Unduh</Button></div>)}</div>}<Pagination page={versionPage} count={versionPages} onChange={(_, page) => { const lifecycle = lifecycleRef.current; loadVersions(lifecycle, historyRequests.current, id, page).catch(() => {}); }} />
        <h2 className="font-bold">Aktivitas</h2>{activityView === 'loading' ? <div>Memuat aktivitas...</div> : activityView === 'error' ? <Alert severity="error">{timelineError}</Alert> : activityView === 'empty' ? <div>Belum ada aktivitas.</div> : <div className="space-y-2">{timelinePageLoading && <LinearProgress />}{activities.map(item => <div key={item.audit_log_id} className="p-3 border rounded"><strong>{item.label}</strong><span> — {item.actor_display_name || 'Akun tidak tersedia'} — {date(item.occurred_at)}</span>{item.reason && <div>Alasan: {item.reason}</div>}{item.changed_fields.length > 0 && <div>Perubahan: {item.changed_fields.join(', ')}</div>}</div>)}<Pagination page={timelinePage} count={timelinePages} onChange={(_, page) => loadTimeline(lifecycleRef.current, timelineRequests.current, id, page)} /></div>}
        </Box>
        <Box role="tabpanel" id="archive-panel-distribution" aria-labelledby="archive-tab-distribution" hidden={tab !== 1} tabIndex={tab === 1 ? 0 : undefined}><InstitutionalDistributionPanel archiveId={id} active={archive.status === 'active' && !archive.deleted_at} /></Box>
        <Box role="tabpanel" id="archive-panel-metadata" aria-labelledby="archive-tab-metadata" hidden={tab !== 2} tabIndex={tab === 2 ? 0 : undefined} className="space-y-4">
        <h2 className="font-bold">Edit metadata</h2><div className="grid md:grid-cols-2 gap-3">{['title', 'document_number', 'document_year', 'document_date', 'received_date', 'description', 'retention_note', 'tags'].map(key => <TextField key={key} label={metadataLabels[key]} multiline={key === 'description' || key === 'retention_note'} minRows={key === 'description' || key === 'retention_note' ? 3 : undefined} className={key === 'description' || key === 'retention_note' ? 'md:col-span-2' : ''} type={key.includes('date') ? 'date' : key === 'document_year' ? 'number' : 'text'} InputLabelProps={key.includes('date') ? { shrink: true } : undefined} value={form[key] || ''} error={Boolean(metadataErrors[key])} helperText={metadataErrors[key]?.join(' ') || ' '} onChange={e => setForm({ ...form, [key]: e.target.value })} />)}<TextField select label="Unit" value={form.unit_id || ''} error={Boolean(metadataErrors.unit_id)} helperText={metadataErrors.unit_id?.join(' ') || ' '} onChange={e => setForm({ ...form, unit_id: e.target.value })}>{units.map(x => <MenuItem key={x.unit_id} value={x.unit_id}>{x.name}</MenuItem>)}</TextField><TextField select label="Akses" value={form.access_level || 'internal'} error={Boolean(metadataErrors.access_level)} helperText={metadataErrors.access_level?.join(' ') || ' '} onChange={e => setForm({ ...form, access_level: e.target.value })}><MenuItem value="internal">Internal</MenuItem><MenuItem value="restricted">Restricted</MenuItem></TextField></div><Button disabled={saving} variant="contained" onClick={() => run(() => arsipApi.updateInstitutionalArchive(id, metadataPayload(form)), 'Metadata berhasil diperbarui.', setMetadataErrors)}>Simpan metadata</Button>
        <h2 className="font-bold">Pindah folder</h2><div className="flex gap-2"><TextField select label="Folder tujuan" value={moveCategory} error={Boolean(moveErrors.category_id)} helperText={moveErrors.category_id?.join(' ') || ' '} onChange={e => setMoveCategory(e.target.value)}><MenuItem value="">Tanpa Folder</MenuItem>{categories.map(x => <MenuItem key={x.category_id} value={x.category_id}>{x.name}</MenuItem>)}</TextField><Button disabled={saving} onClick={() => run(() => arsipApi.moveInstitutionalArchive(id, moveCategory), 'Arsip berhasil dipindahkan.', setMoveErrors)}>Pindahkan</Button></div>
        </Box></div>
    </div>;
}
