import { useCallback, useEffect, useRef, useState } from 'react';
import { Accordion, AccordionDetails, AccordionSummary, Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Pagination, Stack, TextField } from '@mui/material';
import TargetPicker from '../components/TargetPicker';
import { arsipApi } from '../../../libs/arsip_api';
import { formatArsipError } from '../../../libs/arsip_http';
import { distributionActionPolicy, distributionCountLabel, distributionEffectiveStatus, distributionListRequest, distributionPanelController, distributionPreviewConfirmed, distributionRecipientStatus, distributionTargetChange, distributionTargetFingerprint, loadControlledPage, recipientPageRequest, runAuthoritativePublish, runControlledPageRefresh, runDistributionMutation } from './institutionalArchiveUi';

const emptyTargets = { target_role: 'mahasiswa', scope_type: 'specific', target_filters: {}, target_identifiers: [], target_segment_ids: [] };
const emptyForm = { title: '', description: '', expires_at: '' };
const text = value => ['string', 'number'].includes(typeof value) ? String(value) : '-';
export default function InstitutionalDistributionPanel({ archiveId, active }) {
    const currentArchiveId = useRef(String(archiveId)); currentArchiveId.current = String(archiveId);
    const controller = useRef(null); if (!controller.current) controller.current = distributionPanelController(id => currentArchiveId.current === String(id));
    const lock = useRef(false); const [rows, setRows] = useState([]); const [meta, setMeta] = useState({ current_page: 1, last_page: 1 }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [warning, setWarning] = useState(''); const [message, setMessage] = useState('');
    const [form, setForm] = useState(emptyForm); const [targets, setTargets] = useState(emptyTargets); const targetsRef = useRef(targets); targetsRef.current = targets; const [preview, setPreview] = useState(null); const [previewFingerprint, setPreviewFingerprint] = useState(null); const [editing, setEditing] = useState(null); const [pickerSession, setPickerSession] = useState(0); const [viewer, setViewer] = useState(null); const [withdraw, setWithdraw] = useState(null);
    const load = async (capture, page = 1) => { const result = await loadControlledPage({ capture, page, perPage: 10, requestParams: distributionListRequest, rowsKey: 'distributions', request: async params => (await arsipApi.institutionalDistributions(capture.archiveId, params)).data }); return result && { rows: result.rows, meta: result.meta }; };
    const refresh = async (capture, page = 1) => { const data = await load(capture, page); if (data && capture.valid()) { setRows(data.rows); setMeta(data.meta); } return data; };
    useEffect(() => { const owner = controller.current; owner.select(archiveId); lock.current = false; setRows([]); setViewer(null); setWithdraw(null); setEditing(null); setForm(emptyForm); setTargets(emptyTargets); setPreview(null); setPreviewFingerprint(null); setPickerSession(x => x + 1); setError(''); setWarning(''); setMessage(''); setBusy(false); const capture = owner.capture('list'); refresh(capture).catch(async e => { const x = await formatArsipError(e); if (capture.valid()) setError(x.message); }); return () => { if (currentArchiveId.current === String(archiveId)) owner.select(`invalid:${archiveId}`); }; }, [archiveId, active]);
    useEffect(() => () => controller.current.close(), []);
    const action = async request => { const capture = controller.current.beginAction(); if (!capture || lock.current) return false; lock.current = true; setBusy(true); setError(''); setWarning(''); setMessage(''); try { return await runDistributionMutation({ capture, mutate: () => request(capture), refresh: () => { const listCapture = controller.current.capture('list'); return refresh(listCapture, meta.current_page); }, onSuccess: () => setMessage('Distribusi berhasil diperbarui.'), onPartial: () => setWarning('Perubahan tersimpan, tetapi daftar belum berhasil diperbarui'), onError: (e, x) => setError(e?.response?.status === 409 ? `${x.message} Muat ulang data lalu konfirmasi kembali.` : x.message), formatError: formatArsipError }); } finally { lock.current = false; if (controller.current.release(capture)) setBusy(false); } };
    const changeTargets = useCallback(value => { const next = distributionTargetChange(targetsRef.current, value, preview, previewFingerprint); targetsRef.current = next.targets; setTargets(next.targets); setPreview(next.preview); setPreviewFingerprint(next.previewFingerprint); }, [preview, previewFingerprint]);
    const previewTargets = async () => { const payload = structuredClone(targetsRef.current); const fingerprint = distributionTargetFingerprint(payload); const capture = controller.current.capture('target-preview'); try { const data = (await arsipApi.previewInstitutionalDistributionTargets(capture.archiveId, payload)).data.preview; if (capture.valid() && fingerprint === distributionTargetFingerprint(targetsRef.current)) { setPreview(data); setPreviewFingerprint(fingerprint); } } catch (e) { if (capture.valid()) { const x = await formatArsipError(e); if (capture.valid()) setError(x.message); } } };
    const removeTargetIdentifier = identifier => { const next = { ...targetsRef.current, scope_type: 'specific', target_identifiers: (Array.isArray(targetsRef.current.target_identifiers) ? targetsRef.current.target_identifiers : []).filter(item => String(item) !== String(identifier)) }; targetsRef.current = next; setTargets(next); setPreview(null); setPreviewFingerprint(null); setPickerSession(x => x + 1); };
    const openEdit = async row => { if (!active) return; const id = row.distribution_id; const capture = controller.current.capture(`edit:${id}`); try { const [detail, persisted] = await Promise.all([arsipApi.institutionalDistribution(id), arsipApi.institutionalDistributionTargets(id)]); if (!capture.valid() || id !== row.distribution_id) return; const d = detail.data.distribution; const t = persisted.data; setEditing({ id, updated_at: t.updated_at }); setForm({ title: text(d.title) === '-' ? '' : text(d.title), description: text(d.description) === '-' ? '' : text(d.description), expires_at: typeof d.expires_at === 'string' ? new Date(d.expires_at).toISOString().slice(0, 16) : '' }); setTargets(t.criteria); setPreview(null); setPreviewFingerprint(null); setPickerSession(x => x + 1); } catch (e) { if (capture.valid()) { const x = await formatArsipError(e); if (capture.valid()) setError(x.message); } } };
    const showTargets = async row => { const id = row.distribution_id; const capture = controller.current.capture('viewer'); setError(''); try { const data = (await arsipApi.institutionalDistributionTargets(id)).data; if (capture.valid()) setViewer({ type: 'targets', row, rows: Array.isArray(data?.targets) ? data.targets : [], meta: { current_page: 1, last_page: 1 } }); } catch (e) { if (capture.valid()) { const x = await formatArsipError(e); if (capture.valid()) setError(x.message); } } };
    const showRecipients = async (row, page = 1) => { const id = row.distribution_id; const capture = controller.current.capture('viewer'); setError(''); try { const data = (await arsipApi.institutionalDistributionRecipients(id, recipientPageRequest(page))).data; if (capture.valid()) setViewer({ type: 'recipients', row, rows: Array.isArray(data?.recipients) ? data.recipients : [], meta: data?.meta || { current_page: 1, last_page: 1 } }); } catch (e) { if (capture.valid()) { const x = await formatArsipError(e); if (capture.valid()) setError(x.message); } } };
    const publish = row => action(capture => runAuthoritativePublish({ capture, distributionId: row.distribution_id, fetchDistribution: async id => (await arsipApi.institutionalDistribution(id)).data.distribution, fetchTargets: async id => (await arsipApi.institutionalDistributionTargets(id)).data, confirm: source => window.confirm(`Publikasikan ${source.filename} ke target draft tersimpan?`), publish: arsipApi.publishInstitutionalDistribution, refresh: async () => {}, onStale: () => {}, onError: setError, formatError: formatArsipError }));
    const policy = distributionActionPolicy(active);
    return <div className="space-y-3"><h2 className="font-bold">Distribusi mahasiswa/dosen</h2>{!active && <Alert severity="warning">Arsip tidak aktif. Distribusi lama tetap read-only.</Alert>}{error && <Alert severity="error">{error}</Alert>}{warning && <Alert severity="warning">{warning} <Button size="small" onClick={() => { const capture = controller.current.capture('list'); runControlledPageRefresh({ capture, refresh: () => refresh(capture, meta.current_page), onError: setError, formatError: formatArsipError }).then(result => result && setWarning('')); }}>Coba lagi</Button></Alert>}{message && <Alert severity="success">{message}</Alert>}
        {active && <Accordion defaultExpanded><AccordionSummary>{editing ? 'Edit draft' : 'Buat distribusi'}</AccordionSummary><AccordionDetails className="space-y-3"><div className="grid md:grid-cols-2 gap-2"><TextField disabled={!policy.create || busy} label="Judul distribusi" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /><TextField disabled={!policy.create || busy} type="datetime-local" label="Kedaluwarsa" InputLabelProps={{ shrink: true }} value={form.expires_at} onChange={e => setForm({ ...form, expires_at: e.target.value })} /><TextField className="md:col-span-2" multiline minRows={3} disabled={!policy.create || busy} label="Pesan" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></div>
        {targets.scope_type === 'segment' ? <><Alert severity="info">Kriteria segment aktif: ID {targets.target_segment_ids?.join(', ') || '-'}. Membership diselesaikan ulang saat preview/publish.</Alert><Button disabled={!policy.create || busy} onClick={() => { const next = { ...targets, scope_type: 'specific', target_segment_ids: [], target_identifiers: [] }; targetsRef.current = next; setTargets(next); setPreview(null); setPickerSession(x => x + 1); }}>Ganti ke target spesifik/filter</Button></> : <TargetPicker key={pickerSession} value={targets} onChange={changeTargets} disabled={!policy.create || busy} />}
        <div>{distributionPreviewConfirmed(preview, targets, previewFingerprint) ? `${text(preview.total_valid)} target valid · siap disimpan` : 'Preview target wajib sebelum simpan.'}</div>{preview && <div className="rounded border p-3"><strong>Daftar preview target</strong><div className="mt-2 max-h-56 overflow-y-auto divide-y">{[...(Array.isArray(preview.invalid_targets) ? preview.invalid_targets.map(x => ({ ...x, valid: false })) : []), ...(Array.isArray(preview.valid_targets) ? preview.valid_targets.map(x => ({ ...x, valid: true })) : [])].map((target, i) => <div key={`${text(target.identifier)}-${i}`} className={`flex items-center justify-between gap-3 py-2 ${target.valid ? '' : 'text-red-700'}`}><span><b>{text(target.identifier)}</b> · {text(target.name_snapshot ?? target.name)}</span>{targets.scope_type === 'specific' && <Button size="small" color="error" onClick={() => removeTargetIdentifier(target.identifier)}>Batalkan</Button>}</div>)}{!(Array.isArray(preview.valid_targets) && preview.valid_targets.length) && !(Array.isArray(preview.invalid_targets) && preview.invalid_targets.length) && <div className="py-3 text-sm text-zinc-500">Belum ada target.</div>}</div></div>}<Stack direction="row" spacing={1}><Button variant="contained" disabled={!policy.previewTargets || busy} onClick={previewTargets}>{targets.scope_type === 'segment' ? 'Preview target draft' : 'Preview target'}</Button><Button variant="outlined" disabled={busy || !form.title.trim() || !distributionPreviewConfirmed(preview, targets, previewFingerprint)} onClick={() => { const payload = { ...targetsRef.current, title: form.title.trim(), description: form.description || null, expires_at: form.expires_at ? new Date(form.expires_at).toISOString() : null, ...(editing ? { expected_updated_at: editing.updated_at } : {}) }; return action(() => editing ? arsipApi.updateInstitutionalDistribution(editing.id, payload) : arsipApi.createInstitutionalDistribution(archiveId, payload)).then(ok => { if (ok) { setEditing(null); setForm(emptyForm); setTargets(emptyTargets); setPreview(null); setPickerSession(x => x + 1); } }); }}>{editing ? 'Simpan perubahan' : 'Simpan draft'}</Button>{editing && <Button onClick={() => { setEditing(null); setForm(emptyForm); setTargets(emptyTargets); setPreview(null); setPickerSession(x => x + 1); }}>Tutup editor</Button>}</Stack></AccordionDetails></Accordion>}
        <Accordion defaultExpanded><AccordionSummary>Daftar distribusi</AccordionSummary><AccordionDetails className="space-y-3">{rows.map(row => { const status = distributionEffectiveStatus(row); return <div key={row.distribution_id} className="flex flex-wrap gap-2 items-center p-2 border rounded"><strong>{row.title}</strong><span>Status: {status}</span><span>{distributionCountLabel(row)}</span>{status === 'draft' ? <><Button disabled={busy} onClick={() => showTargets(row)}>Lihat target</Button>{active && <><Button disabled={busy} onClick={() => openEdit(row)}>Edit draft</Button><Button disabled={!policy.publish || busy} onClick={() => publish(row)}>Publikasikan</Button><Button color="error" disabled={busy} onClick={() => window.confirm('Batalkan draft ini?') && action(async () => { const detail = (await arsipApi.institutionalDistribution(row.distribution_id)).data.distribution; await arsipApi.cancelInstitutionalDistribution(row.distribution_id, { expected_updated_at: detail.updated_at }); })}>Batalkan draft</Button></>}</> : <><Button disabled={busy} onClick={() => showRecipients(row)}>Lihat penerima</Button>{status === 'published' && active && <Button color="error" disabled={busy} onClick={() => setWithdraw({ row, reason: '' })}>Tarik akses</Button>}</>}</div>; })}<Pagination page={meta.current_page || 1} count={meta.last_page || 1} onChange={(_, page) => { const capture = controller.current.capture('list'); return runControlledPageRefresh({ capture, refresh: () => refresh(capture, page), onError: setError, formatError: formatArsipError }); }} /></AccordionDetails></Accordion>
        {viewer && <Dialog open fullWidth maxWidth="lg" onClose={() => setViewer(null)} aria-label={viewer.type === 'targets' ? 'Target draft' : 'Penerima materialized'}><DialogContent dividers><Stack direction="row" justifyContent="space-between" alignItems="center"><h3 className="font-bold">{viewer.type === 'targets' ? 'Target draft' : 'Penerima materialized'}: {text(viewer.row.title)}</h3><Stack direction="row" spacing={1}>{viewer.type === 'targets' && active && <Button onClick={() => { openEdit(viewer.row); setViewer(null); }}>Tambah/hapus target</Button>}<Button onClick={() => setViewer(null)}>Tutup</Button></Stack></Stack><div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{(viewer.type === 'targets' ? ['Identifier', 'Nama', 'Angkatan', 'Prodi', 'Status akademik'] : ['Identifier', 'Nama', 'Status akses', 'Pertama', 'Terakhir', 'Jumlah']).map(x => <th scope="col" key={x} className="p-2 text-left border-b">{x}</th>)}</tr></thead><tbody>{viewer.rows.map((x, i) => <tr key={x.recipient_id || `${x.identifier}-${i}`}><td className="p-2">{text(x.identifier)}</td><td className="p-2">{text(x.name_snapshot)}</td>{viewer.type === 'targets' ? <><td className="p-2">{text(x.angkatan_snapshot)}</td><td className="p-2">{text(x.prodi_snapshot)}</td><td className="p-2">{text(x.status_snapshot)}</td></> : <><td className="p-2">{distributionRecipientStatus(x, viewer.row)}</td><td className="p-2">{text(x.first_downloaded_at)}</td><td className="p-2">{text(x.last_downloaded_at)}</td><td className="p-2">{text(x.download_count ?? 0)}</td></>}</tr>)}{viewer.rows.length === 0 && <tr><td className="p-2" colSpan={viewer.type === 'targets' ? 5 : 6}>Belum ada data.</td></tr>}</tbody></table></div>{viewer.type === 'recipients' && <Stack direction="row" spacing={1} mt={1}><Button disabled={(viewer.meta?.current_page || 1) <= 1} onClick={() => showRecipients(viewer.row, viewer.meta.current_page - 1)}>Sebelumnya</Button><Button disabled={(viewer.meta?.current_page || 1) >= (viewer.meta?.last_page || 1)} onClick={() => showRecipients(viewer.row, viewer.meta.current_page + 1)}>Berikutnya</Button></Stack>}</DialogContent></Dialog>}
        <Dialog open={Boolean(withdraw)} onClose={() => !busy && setWithdraw(null)}><DialogTitle>Tarik distribusi?</DialogTitle><DialogContent><TextField autoFocus fullWidth multiline label="Alasan wajib" value={withdraw?.reason || ''} onChange={e => setWithdraw({ ...withdraw, reason: e.target.value })} /></DialogContent><DialogActions><Button onClick={() => setWithdraw(null)}>Batal</Button><Button color="error" disabled={busy || !withdraw?.reason.trim()} onClick={() => action(() => arsipApi.withdrawInstitutionalDistribution(withdraw.row.distribution_id, withdraw.reason)).then(ok => ok && setWithdraw(null))}>Tarik</Button></DialogActions></Dialog>
    </div>;
}
